excluded:
  - .build
  - Package.swift

disabled_rules:
  - inclusive_language
  - large_tuple

line_length:
  warning: 170
  error: 200

type_body_length:
  warning: 400
  error: 500

function_body_length:
  warning: 75
  error: 100

file_length:
  warning: 500
  error: 600
